#!/bin/bash

echo "🔄 TESTE COMPLETO DE AUTENTICAÇÃO E API DO MERCADO LIVRE"
echo "========================================================"
echo ""

BASE_URL="https://peepers.vercel.app"

echo "1️⃣ TESTANDO STATUS DA APLICAÇÃO..."
echo "-----------------------------------"
echo "Health Check:"
curl -s -w "\nStatus: %{http_code}\n" "$BASE_URL/api/health" | head -5
echo ""

echo "2️⃣ TESTANDO AUTENTICAÇÃO SEM LOGIN..."
echo "-------------------------------------"
echo "Status de autenticação (deve retornar 401):"
curl -s -w "\nStatus: %{http_code}\n" "$BASE_URL/api/auth/me"
echo ""

echo "Produtos sem autenticação (deve retornar 401):"
curl -s -w "\nStatus: %{http_code}\n" "$BASE_URL/api/products?format=summary&limit=5"
echo ""

echo "3️⃣ INICIANDO FLUXO DE AUTENTICAÇÃO..."
echo "-------------------------------------"
echo "🔗 URL para autenticação (abra no navegador):"
echo "$BASE_URL/api/auth/mercado-livre"
echo ""
echo "📋 INSTRUÇÕES:"
echo "1. Abra a URL acima no navegador"
echo "2. Complete o login no Mercado Livre"
echo "3. Após o redirecionamento, volte aqui e pressione ENTER"
echo ""
read -p "⏳ Pressione ENTER após completar a autenticação..."

echo ""
echo "4️⃣ TESTANDO APÓS AUTENTICAÇÃO..."
echo "--------------------------------"
echo "⚠️  IMPORTANTE: Os próximos testes precisam usar os cookies do navegador"
echo "Para testar com cookies, use as DevTools do navegador ou:"
echo ""
echo "Teste manual no navegador:"
echo "- $BASE_URL/api/auth/me"
echo "- $BASE_URL/api/products?format=summary&limit=10"
echo ""

echo "5️⃣ COMANDOS PARA TESTE MANUAL..."
echo "--------------------------------"
echo "Copie e execute no navegador (DevTools Console):"
echo ""
echo "// Teste de autenticação"
echo "fetch('$BASE_URL/api/auth/me', {credentials: 'include'})"
echo "  .then(r => r.json())"
echo "  .then(console.log)"
echo ""
echo "// Teste de produtos"
echo "fetch('$BASE_URL/api/products?format=summary&limit=10', {credentials: 'include'})"
echo "  .then(r => r.json())"
echo "  .then(console.log)"
echo ""

echo "6️⃣ PRÓXIMOS PASSOS..."
echo "---------------------"
echo "Após autenticação bem-sucedida:"
echo "1. Acesse: $BASE_URL/admin/produtos"
echo "2. Verifique se os produtos reais são carregados"
echo "3. Confirme se não há mais dados mock"
echo ""

echo "✅ Script preparado! Execute a autenticação e teste as APIs."